require: rubocop-rspec
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/ExampleLength:
  Max: 6
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - being
